permalink: /:year:month:day/:title
url: #Your url here
baseurl: /project

# variables
name: 헬로우 월드!
description: Welcome to come here!
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true

# Math equation 
markdown: kramdown 
highlighter: rouge 
lsi: false 
excerpt_separator: "\n\n" 
incremental: false
